typedef struct camoramic_gst_fx_s {
  char* name;
  char* friendly_name;
  char* param_name;
  char* param2_name;
  int param_is_int;
  double param;
  double param2;
  GdkPixbuf *preview;
} camoramic_gst_fx;

extern GstElement *pipeline;
extern GstElement *src;
extern GstElement *videoconvert;
extern GstElement *decoder;
extern GstElement *capsfilter;
extern GstElement *frameratefilter;
extern GstElement *tee;
extern GstElement *preview_queue;
extern GstElement *preview_videoconvert;
extern GstElement *preview_overlay;
extern GstElement *preview_sink;
extern GstElement *pixbuf_queue;
extern GstElement *pixbuf_sink;
extern GstElement *fx;
extern GstElement *fx_videoconvert;
extern GstElement **fx_preview_sink;
extern double overlay_opacity;
extern camoramic_gst_fx* fx_list;
extern int fx_count;
extern int fx_current;
extern int video_recording;
void camoramic_gst_create_pipeline();
void camoramic_gst_check_element(GstElement *elem, char *name);
void camoramic_gst_take_photo();
void camoramic_gst_rebuild_pipeline_v4lsrc();
void camoramic_gst_init_fx();
void camoramic_gst_set_fx(int fxno);
void camoramic_gst_create_fx_preview();
void camoramic_gst_destroy_fx_preview();
void camoramic_gst_record_start();
void camoramic_gst_record_stop();
int camoramic_gst_check_if_element_exists(char *name);
